name: unipal_app
description: UniPal mobile app made with Flutter SDK

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  animated_custom_dropdown: ^1.2.1
  animations: ^2.0.2
  another_flushbar: ^1.10.29
  audioplayers: ^0.20.1
  cached_network_image: ^3.2.1
  clock: ^1.1.0
  cupertino_icons: ^1.0.4
  dio: ^4.0.6
  dio_cache_interceptor: ^3.2.7
  dio_cache_interceptor_hive_store: ^3.1.1
  firebase_core: ^1.17.0
  firebase_storage: ^10.2.16
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.4
  flutter_secure_storage: ^5.0.2
  flutter_spinkit: ^5.1.0
  freezed_annotation: ^2.0.3
  golden_toolkit: ^0.13.0
  google_fonts: ^2.3.3
  hooks_riverpod: ^2.0.0-dev.7
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  json_annotation: ^4.5.0
  lottie: ^1.3.0
  mobile_scanner: ^1.1.0
  mockito: ^5.2.0
  path: ^1.8.1
  path_provider: ^2.0.10
  sentry_flutter: ^6.5.1
  shared_preferences: ^2.0.15
  table_sticky_headers: ^2.0.0
  time: ^2.1.0

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/lottie/
    - assets/sounds/
